#!/bin/sh

if [[ "$1" == "--title" ]]; then
  s=$(playerctl status)
  if [[ $s == "" ]]; then
    echo "Not Playing"
  else
    playerctl metadata title
  fi
elif [[ "$1" == "--artist" ]]; then
  playerctl metadata artist
elif [[ "$1" == "--previous" ]]; then
  playerctl previous
elif [[ "$1" == "--next" ]]; then
  playerctl next
elif [[ "$1" == "--status" ]]; then
  s=$(playerctl status)
  if [[ $s == "Playing" ]]; then
    echo "" 
  else
    echo "喇"
  fi
elif [[ "$1" == "--cover" ]]; then
  s=$(playerctl status)
  if [[ $s == "Playing" ]]; then
    c=$(playerctl metadata mpris:artUrl)
    echo "$c"
  else
    echo "Not Playing"
  fi
fi
