#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd -c ~/.config/bspwm/sxhkdrc &

xsetroot -cursor_name left_ptr &
xinput --set-prop 'Glorious Model O' 'libinput Accel Profile Enabled' 0, 1 &
# picom --config ~/.config/bspwm/picom/picom.conf --experimental-backends &
picom --config ~/.config/bspwm/picom/picom_alternate.conf &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
dunst -config ~/.config/bspwm/dunst/dunstrc &
export _JAVA_AWT_WM_NONEREPARENTING=1 &
# ~/.config/bspwm/polybar/alternate_polybar/new_bar/launch.sh &
~/.config/bspwm/eww/launch.sh &
pkill ewwFullscreenFix.sh; ~/.config/bspwm/scripts/ewwFullscreenFix.sh &
# ~/.config/bspwm/alternate_polybar/bottom_dock/launch.sh &
# ~/.config/bspwm/polybar/alternate_polybar/non_floating_bar/launch.sh &
# ~/.config/bspwm/polybar/launch.sh &
# ~/.config/bspwm/polybar/alternate_polybar/launch.sh &
~/.config/conky/Mimosa-Dark/start.sh &
killall plank && plank &
~/.fehbg &

bspc monitor -d 1 2 3 4 5

bspc config border_width         0
bspc config border_radius        0
bspc config window_gap          12

bspc config focused_border_color "#89b4fa"
# bspc config focused_border_color "#a6e3a1"
# bspc config focused_border_color "#1d1d2d"

bspc config top_padding 0
bspc config bottom_padding 70
bspc config left_padding 70
bspc config right_padding 0
