#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd -c $HOME/.config/bspwm/sxhkdrc &
$HOME/.config/bspwm/autostart.sh &

bspc monitor -d 1 2 3 4 5

bspc config border_width         0
bspc config window_gap          12

bspc config top_padding 80
bspc config bottom_padding 80
bspc config left_padding 80
bspc config right_padding 80
