#!/bin/sh

alacritty="$HOME/.config/bspwm/alacritty/colors.yml"
gtk="$HOME/.config/gtk-3.0/settings.ini"
gtkrc="$HOME/.gtkrc-2.0"

sed -i '/colors: */c\colors: *mocha' $alacritty
sed -i '/gtk-theme-name=/c\gtk-theme-name=Catppuccin-Mocha' $gtk
sed -i '/gtk-theme-name=/c\gtk-theme-name=Catppuccin-Mocha' $gtkrc
